displayName=Group Pk Loot Tracker
author=Alec Sherlock
description=Tacks pk loot values for groups, generates splits, messages to Discord
tags=group, pk, loot, tracker, discord, clan
version='1.0-SNAPSHOT'
plugins=com.alecsherlock.grouppkloottracker.GroupPkLootTrackerPlugin
build=standard